//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiWebServices.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://miwebservices.com/", ConfigurationName="ServiceReference.ServicesSoap")]
    public interface ServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://miwebservices.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://miwebservices.com/HelloWorld", ReplyAction="*")]
        MiWebServices.ServiceReference.HelloWorldResponse HelloWorld(MiWebServices.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://miwebservices.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MiWebServices.ServiceReference.HelloWorldResponse> HelloWorldAsync(MiWebServices.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HoraResult del espacio de nombres http://miwebservices.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://miwebservices.com/Hora", ReplyAction="*")]
        MiWebServices.ServiceReference.HoraResponse Hora(MiWebServices.ServiceReference.HoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://miwebservices.com/Hora", ReplyAction="*")]
        System.Threading.Tasks.Task<MiWebServices.ServiceReference.HoraResponse> HoraAsync(MiWebServices.ServiceReference.HoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://miwebservices.com/Suma", ReplyAction="*")]
        int Suma(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://miwebservices.com/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumaAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://miwebservices.com/", Order=0)]
        public MiWebServices.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MiWebServices.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://miwebservices.com/", Order=0)]
        public MiWebServices.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MiWebServices.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://miwebservices.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hora", Namespace="http://miwebservices.com/", Order=0)]
        public MiWebServices.ServiceReference.HoraRequestBody Body;
        
        public HoraRequest() {
        }
        
        public HoraRequest(MiWebServices.ServiceReference.HoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HoraRequestBody {
        
        public HoraRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HoraResponse", Namespace="http://miwebservices.com/", Order=0)]
        public MiWebServices.ServiceReference.HoraResponseBody Body;
        
        public HoraResponse() {
        }
        
        public HoraResponse(MiWebServices.ServiceReference.HoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://miwebservices.com/")]
    public partial class HoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HoraResult;
        
        public HoraResponseBody() {
        }
        
        public HoraResponseBody(string HoraResult) {
            this.HoraResult = HoraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesSoapChannel : MiWebServices.ServiceReference.ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesSoapClient : System.ServiceModel.ClientBase<MiWebServices.ServiceReference.ServicesSoap>, MiWebServices.ServiceReference.ServicesSoap {
        
        public ServicesSoapClient() {
        }
        
        public ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiWebServices.ServiceReference.HelloWorldResponse MiWebServices.ServiceReference.ServicesSoap.HelloWorld(MiWebServices.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MiWebServices.ServiceReference.HelloWorldRequest inValue = new MiWebServices.ServiceReference.HelloWorldRequest();
            inValue.Body = new MiWebServices.ServiceReference.HelloWorldRequestBody();
            MiWebServices.ServiceReference.HelloWorldResponse retVal = ((MiWebServices.ServiceReference.ServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiWebServices.ServiceReference.HelloWorldResponse> MiWebServices.ServiceReference.ServicesSoap.HelloWorldAsync(MiWebServices.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiWebServices.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            MiWebServices.ServiceReference.HelloWorldRequest inValue = new MiWebServices.ServiceReference.HelloWorldRequest();
            inValue.Body = new MiWebServices.ServiceReference.HelloWorldRequestBody();
            return ((MiWebServices.ServiceReference.ServicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiWebServices.ServiceReference.HoraResponse MiWebServices.ServiceReference.ServicesSoap.Hora(MiWebServices.ServiceReference.HoraRequest request) {
            return base.Channel.Hora(request);
        }
        
        public string Hora() {
            MiWebServices.ServiceReference.HoraRequest inValue = new MiWebServices.ServiceReference.HoraRequest();
            inValue.Body = new MiWebServices.ServiceReference.HoraRequestBody();
            MiWebServices.ServiceReference.HoraResponse retVal = ((MiWebServices.ServiceReference.ServicesSoap)(this)).Hora(inValue);
            return retVal.Body.HoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiWebServices.ServiceReference.HoraResponse> MiWebServices.ServiceReference.ServicesSoap.HoraAsync(MiWebServices.ServiceReference.HoraRequest request) {
            return base.Channel.HoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiWebServices.ServiceReference.HoraResponse> HoraAsync() {
            MiWebServices.ServiceReference.HoraRequest inValue = new MiWebServices.ServiceReference.HoraRequest();
            inValue.Body = new MiWebServices.ServiceReference.HoraRequestBody();
            return ((MiWebServices.ServiceReference.ServicesSoap)(this)).HoraAsync(inValue);
        }
        
        public int Suma(int a, int b) {
            return base.Channel.Suma(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SumaAsync(int a, int b) {
            return base.Channel.SumaAsync(a, b);
        }
    }
}
